{{- if and .Values.backup.enabled .Values.backup.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "planka.backupServiceAccountName" . }}
  labels:
    {{- include "planka.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- with .Values.backup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
