name: "✨ Feature Request"
description: Suggest a feature or enhancement to improve Planka.
labels: ["Type: Idea"]
body:
  -   type: dropdown
      id: idea-type
      attributes:
        label: Is this a feature for the backend or frontend?
        multiple: true
        options:
          - Backend
          - Frontend
      validations:
        required: true
  -   type: textarea
      id: feature
      attributes:
        label: What would you like?
        description: A clear description of the feature or enhancement wanted.
        placeholder: I'd like to be able to...
      validations:
        required: true
  -   type: textarea
      id: reason
      attributes:
        label: Why is this needed?
        description: A clear description of why this would be useful to have.
        placeholder: I want this because...
  -   type: textarea
      id: other
      attributes:
        label: Other information
        placeholder: Any other details?
