name: Build and push Docker base image

on:
  push:
    paths:
      - ./Dockerfile.base
    branches:
      - master

env:
  ALPINE_VERSION: 3.15

jobs:
  build-and-push-docker-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile.base
          build_args:
            - ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          push: true
          tags: |
            ghcr.io/plankanban/planka:base-latest
            ghcr.io/plankanban/planka:base-${{ env.ALPINE_VERSION }}
